/*
THIS IS A GENERATED/BUNDLED FILE BY ESBUILD
if you want to view the source, please visit the github repository of this plugin
*/

var __defProp = Object.defineProperty;
var __getOwnPropDesc = Object.getOwnPropertyDescriptor;
var __getOwnPropNames = Object.getOwnPropertyNames;
var __hasOwnProp = Object.prototype.hasOwnProperty;
var __esm = (fn, res) => function __init() {
  return fn && (res = (0, fn[__getOwnPropNames(fn)[0]])(fn = 0)), res;
};
var __export = (target, all) => {
  for (var name in all)
    __defProp(target, name, { get: all[name], enumerable: true });
};
var __copyProps = (to, from, except, desc) => {
  if (from && typeof from === "object" || typeof from === "function") {
    for (let key of __getOwnPropNames(from))
      if (!__hasOwnProp.call(to, key) && key !== except)
        __defProp(to, key, { get: () => from[key], enumerable: !(desc = __getOwnPropDesc(from, key)) || desc.enumerable });
  }
  return to;
};
var __toCommonJS = (mod) => __copyProps(__defProp({}, "__esModule", { value: true }), mod);

// booxClient.ts
var booxClient_exports = {};
__export(booxClient_exports, {
  BooxClient: () => BooxClient
});
var BooxClient;
var init_booxClient = __esm({
  "booxClient.ts"() {
    BooxClient = class {
      constructor(ip, port = 8085) {
        this.baseUrl = `http://${ip}:${port}`;
      }
      /**
       * List all files in a directory on the Boox device.
       * Uses /api/storage endpoint with dir param.
       */
      async listFiles(dir) {
        const args = JSON.stringify({
          dir,
          limit: 200,
          offset: 0,
          sortBy: "CreationTime",
          sortOrder: "Desc",
          refresh: true
        });
        const url = `${this.baseUrl}/api/storage?args=${encodeURIComponent(args)}`;
        const response = await fetch(url);
        if (!response.ok) {
          throw new Error(`BooxDrop returned ${response.status} for dir: ${dir}`);
        }
        const json = await response.json();
        if (!json.successful) {
          throw new Error(`BooxDrop API error (code ${json.code}) for dir: ${dir}`);
        }
        return json.data.list.filter(
          (f) => !f.dir && f.name.toLowerCase().endsWith(".pdf")
        );
      }
      /**
       * Download a file from the Boox device.
       * Returns an ArrayBuffer of the raw file bytes.
       */
      async downloadFile(devicePath) {
        const url = `${this.baseUrl}/api/storage/file?args=${encodeURIComponent(devicePath)}&sender=web`;
        const response = await fetch(url);
        if (!response.ok) {
          throw new Error(`Failed to download ${devicePath}: HTTP ${response.status}`);
        }
        return response.arrayBuffer();
      }
      /**
       * Quick connectivity check — tries to list the root storage.
       * Returns true if device is reachable, false otherwise.
       */
      async isReachable() {
        try {
          const args = JSON.stringify({
            dir: "/storage/emulated/0",
            limit: 1,
            offset: 0,
            sortBy: "CreationTime",
            sortOrder: "Desc",
            refresh: false
          });
          const url = `${this.baseUrl}/api/storage?args=${encodeURIComponent(args)}`;
          const response = await fetch(url, { signal: AbortSignal.timeout(3e3) });
          return response.ok;
        } catch (e) {
          return false;
        }
      }
    };
  }
});

// main.ts
var main_exports = {};
__export(main_exports, {
  default: () => BooxSyncPlugin
});
module.exports = __toCommonJS(main_exports);
var import_obsidian2 = require("obsidian");
init_booxClient();

// syncModal.ts
var import_obsidian = require("obsidian");
var SyncModal = class extends import_obsidian.Modal {
  constructor(app, candidates, onSync) {
    super(app);
    this.isSyncing = false;
    this.candidates = candidates;
    this.onSync = onSync;
  }
  onOpen() {
    const { contentEl } = this;
    contentEl.empty();
    contentEl.createEl("h2", { text: "Boox Notes Sync" });
    const newCount = this.candidates.filter((c) => c.status === "new").length;
    const changedCount = this.candidates.filter((c) => c.status === "changed").length;
    if (this.candidates.length === 0) {
      contentEl.createEl("p", {
        text: "\u2713 Everything is up to date. No new or changed notes found.",
        cls: "boox-sync-empty"
      });
      new import_obsidian.Setting(contentEl).addButton(
        (btn) => btn.setButtonText("Close").onClick(() => this.close())
      );
      return;
    }
    contentEl.createEl("p", {
      text: `Found ${newCount} new and ${changedCount} changed note(s) on your Boox device.`,
      cls: "boox-sync-summary"
    });
    new import_obsidian.Setting(contentEl).setName("Selection").addButton(
      (btn) => btn.setButtonText("Select All").onClick(() => {
        this.candidates.forEach((c) => c.selected = true);
        this.refresh();
      })
    ).addButton(
      (btn) => btn.setButtonText("Deselect All").onClick(() => {
        this.candidates.forEach((c) => c.selected = false);
        this.refresh();
      })
    );
    contentEl.createEl("hr");
    const newNotes = this.candidates.filter((c) => c.status === "new");
    if (newNotes.length > 0) {
      contentEl.createEl("h3", { text: `\u{1F195} New (${newNotes.length})` });
      this.renderCandidateList(contentEl, newNotes);
    }
    const changedNotes = this.candidates.filter((c) => c.status === "changed");
    if (changedNotes.length > 0) {
      contentEl.createEl("h3", { text: `\u270F\uFE0F Changed (${changedNotes.length})` });
      this.renderCandidateList(contentEl, changedNotes);
    }
    contentEl.createEl("hr");
    new import_obsidian.Setting(contentEl).addButton((btn) => {
      btn.setButtonText(`Sync Selected`).setCta().onClick(async () => {
        if (this.isSyncing) return;
        const selected = this.candidates.filter((c) => c.selected);
        if (selected.length === 0) {
          new import_obsidian.Notice("No notes selected.");
          return;
        }
        this.isSyncing = true;
        btn.setButtonText("Syncing...").setDisabled(true);
        try {
          await this.onSync(selected);
          this.close();
        } catch (e) {
          new import_obsidian.Notice(`Sync failed: ${e.message}`);
          btn.setButtonText("Retry").setDisabled(false);
          this.isSyncing = false;
        }
      });
    });
  }
  renderCandidateList(container, notes) {
    for (const candidate of notes) {
      const setting = new import_obsidian.Setting(container).setName(candidate.name).setDesc(this.formatMeta(candidate)).addToggle((toggle) => {
        toggle.setValue(candidate.selected).onChange((val) => {
          candidate.selected = val;
        });
      });
      setting.settingEl.addClass("boox-sync-item");
    }
  }
  formatMeta(f) {
    const date = new Date(f.updatedAt).toLocaleString();
    const kb = Math.round(f.size / 1024);
    return `${kb} KB \xB7 Last modified: ${date}`;
  }
  refresh() {
    this.onOpen();
  }
  onClose() {
    this.contentEl.empty();
  }
};

// main.ts
var DEFAULT_SETTINGS = {
  booxIp: "",
  booxPort: 8085,
  booxSourceDir: "/storage/emulated/0/note/obsidian-sync",
  vaultTargetDir: "boox"
};
var BooxSyncPlugin = class extends import_obsidian2.Plugin {
  async onload() {
    await this.loadSettings();
    this.addRibbonIcon("tablet-smartphone", "Sync Boox Notes", () => {
      this.runSync();
    });
    this.addCommand({
      id: "sync-boox-notes",
      name: "Sync Boox Notes",
      callback: () => this.runSync()
    });
    this.addSettingTab(new BooxSyncSettingTab(this.app, this));
  }
  onunload() {
  }
  // ─── Core sync flow ────────────────────────────────────────────────────────
  async runSync() {
    if (!this.settings.booxIp) {
      new import_obsidian2.Notice("Boox Sync: Please set your Boox IP address in the plugin settings.");
      return;
    }
    const client = new BooxClient(this.settings.booxIp, this.settings.booxPort);
    const notice = new import_obsidian2.Notice("Boox Sync: Connecting to device...", 0);
    const reachable = await client.isReachable();
    notice.hide();
    if (!reachable) {
      new import_obsidian2.Notice(
        `Boox Sync: Cannot reach device at ${this.settings.booxIp}:${this.settings.booxPort}.
Make sure BooxDrop is active and you're on the same network.`,
        8e3
      );
      return;
    }
    let deviceFiles;
    try {
      deviceFiles = await client.listFiles(this.settings.booxSourceDir);
    } catch (e) {
      new import_obsidian2.Notice(`Boox Sync: Failed to list files \u2014 ${e.message}`, 6e3);
      return;
    }
    if (deviceFiles.length === 0) {
      new import_obsidian2.Notice(
        `Boox Sync: No PDF files found in ${this.settings.booxSourceDir}.
Export your notes to that folder on the device first.`,
        8e3
      );
      return;
    }
    const candidates = await this.buildCandidates(deviceFiles);
    new SyncModal(this.app, candidates, async (selected) => {
      await this.downloadAndSave(client, selected);
    }).open();
  }
  /**
   * For each file on the device, check if it exists in the vault.
   * Mark as "new" or "changed" accordingly.
   */
  async buildCandidates(deviceFiles) {
    const candidates = [];
    for (const file of deviceFiles) {
      const vaultPath = (0, import_obsidian2.normalizePath)(`${this.settings.vaultTargetDir}/${file.name}`);
      const existing = this.app.vault.getAbstractFileByPath(vaultPath);
      if (!existing) {
        candidates.push({ ...file, status: "new", selected: true });
      } else if (existing instanceof import_obsidian2.TFile) {
        const vaultModTime = existing.stat.mtime;
        if (file.updatedAt > vaultModTime) {
          candidates.push({ ...file, status: "changed", selected: true });
        }
      }
    }
    return candidates;
  }
  /**
   * Download each selected file and write it to the vault.
   */
  async downloadAndSave(client, selected) {
    await this.ensureFolder(this.settings.vaultTargetDir);
    let successCount = 0;
    const errors = [];
    for (const candidate of selected) {
      try {
        const data = await client.downloadFile(candidate.path);
        const vaultPath = (0, import_obsidian2.normalizePath)(`${this.settings.vaultTargetDir}/${candidate.name}`);
        const existing = this.app.vault.getAbstractFileByPath(vaultPath);
        if (existing instanceof import_obsidian2.TFile) {
          await this.app.vault.modifyBinary(existing, data);
        } else {
          await this.app.vault.createBinary(vaultPath, data);
        }
        successCount++;
      } catch (e) {
        errors.push(`${candidate.name}: ${e.message}`);
      }
    }
    if (errors.length === 0) {
      new import_obsidian2.Notice(`Boox Sync: \u2713 Synced ${successCount} note(s) to /${this.settings.vaultTargetDir}`);
    } else {
      new import_obsidian2.Notice(
        `Boox Sync: Synced ${successCount}/${selected.length} notes.
Errors:
${errors.join("\n")}`,
        1e4
      );
    }
  }
  /**
   * Create a folder in the vault if it doesn't exist yet.
   */
  async ensureFolder(folderPath) {
    const parts = folderPath.split("/").filter(Boolean);
    let current = "";
    for (const part of parts) {
      current = current ? `${current}/${part}` : part;
      if (!this.app.vault.getAbstractFileByPath(current)) {
        await this.app.vault.createFolder(current);
      }
    }
  }
  // ─── Settings persistence ──────────────────────────────────────────────────
  async loadSettings() {
    this.settings = Object.assign({}, DEFAULT_SETTINGS, await this.loadData());
  }
  async saveSettings() {
    await this.saveData(this.settings);
  }
};
var BooxSyncSettingTab = class extends import_obsidian2.PluginSettingTab {
  constructor(app, plugin) {
    super(app, plugin);
    this.plugin = plugin;
  }
  display() {
    const { containerEl } = this;
    containerEl.empty();
    containerEl.createEl("h2", { text: "Boox Sync Settings" });
    containerEl.createEl("p", {
      text: "Make sure BooxDrop is enabled on your device and both devices are on the same WiFi network.",
      cls: "setting-item-description"
    });
    new import_obsidian2.Setting(containerEl).setName("Boox Device IP").setDesc("The IP address shown in the BooxDrop app on your device (e.g. 192.168.1.45).").addText(
      (text) => text.setPlaceholder("192.168.1.45").setValue(this.plugin.settings.booxIp).onChange(async (value) => {
        this.plugin.settings.booxIp = value.trim();
        await this.plugin.saveSettings();
      })
    );
    new import_obsidian2.Setting(containerEl).setName("BooxDrop Port").setDesc("Default is 8085. Only change if your device shows a different port.").addText(
      (text) => text.setPlaceholder("8085").setValue(String(this.plugin.settings.booxPort)).onChange(async (value) => {
        const port = parseInt(value.trim(), 10);
        if (!isNaN(port) && port > 0 && port < 65536) {
          this.plugin.settings.booxPort = port;
          await this.plugin.saveSettings();
        }
      })
    );
    new import_obsidian2.Setting(containerEl).setName("Notes Folder on Device").setDesc(
      "Absolute path to the folder on your Boox where you export notes. Export your handwritten notes as PDF (Vector) to this folder."
    ).addText(
      (text) => text.setPlaceholder("/storage/emulated/0/note/obsidian-sync").setValue(this.plugin.settings.booxSourceDir).onChange(async (value) => {
        this.plugin.settings.booxSourceDir = value.trim();
        await this.plugin.saveSettings();
      })
    );
    new import_obsidian2.Setting(containerEl).setName("Vault Target Folder").setDesc("Folder inside your Obsidian vault where notes will be saved. Will be created if it doesn't exist.").addText(
      (text) => text.setPlaceholder("boox").setValue(this.plugin.settings.vaultTargetDir).onChange(async (value) => {
        this.plugin.settings.vaultTargetDir = value.trim().replace(/^\/|\/$/g, "");
        await this.plugin.saveSettings();
      })
    );
    containerEl.createEl("h3", { text: "Connection" });
    new import_obsidian2.Setting(containerEl).setName("Test Connection").setDesc("Check if your Boox device is reachable on the current network.").addButton(
      (btn) => btn.setButtonText("Test").onClick(async () => {
        if (!this.plugin.settings.booxIp) {
          new import_obsidian2.Notice("Please enter a device IP first.");
          return;
        }
        btn.setButtonText("Testing...").setDisabled(true);
        const { BooxClient: BooxClient2 } = await Promise.resolve().then(() => (init_booxClient(), booxClient_exports));
        const client = new BooxClient2(
          this.plugin.settings.booxIp,
          this.plugin.settings.booxPort
        );
        const ok = await client.isReachable();
        btn.setButtonText("Test").setDisabled(false);
        new import_obsidian2.Notice(
          ok ? `\u2713 Connected to ${this.plugin.settings.booxIp}:${this.plugin.settings.booxPort}` : `\u2717 Cannot reach device. Is BooxDrop active?`,
          5e3
        );
      })
    );
    containerEl.createEl("h3", { text: "How to use" });
    const steps = containerEl.createEl("ol");
    [
      "On your Boox: open a note \u2192 top-right menu \u2192 Export \u2192 choose PDF (Vector).",
      `Save the exported PDF to the folder you configured above (default: note/obsidian-sync/).`,
      "On your PC: make sure BooxDrop is active on the device.",
      'Click the tablet icon in the Obsidian ribbon, or run the "Sync Boox Notes" command.',
      "Select which notes to sync in the dialog and click Sync Selected."
    ].forEach((step) => steps.createEl("li", { text: step }));
  }
};
